export const PATHNAME = {
  HOME: "/home",
  DASHBOARD: "/dashboard",
  COMMING_SOON: "/comming-soon",
  AUTH: {
    LOGIN: "/login",
    REGISTER: "/register",
  },
  ORDER: {
    INDEX: "/order",
    CREATE: "/order/create",
    DETAIL: "/order/:id",
    EDIT: "/order/edit/:id",
  },
  SHOP: {
    INDEX: "/shop",
    CREATE: "/shop/create",
    DETAIL: "/shop/:id",
    EDIT: "/shop/edit/:id",
    EDIT_ID: (id?: string) => `/shop/edit/${id}`,
    DETAIL_ID: (id?: string) => `/shop/${id}`,
  },
  PRODUCT: {
    INDEX: "/product",
    CREATE: "/product/create",
    DETAIL: "/product/:id",
    EDIT: "/product/edit/:id",
  },
  USER: {
    INDEX: "/user",
    CREATE: "/user/create",
    DETAIL: "/user/:id",
    EDIT: "/user/edit/:id",
    EDIT_ID: (id?: string) => `/user/edit/${id}`,
    DETAIL_ID: (id?: string) => `/user/${id}`,
  },
  LOCATION: {
    INDEX: "/location",
    CREATE: "/location/create",
    DETAIL: "/location/:id",
    EDIT: "/location/edit/:id",
    EDIT_ID: (id?: string) => `/location/edit/${id}`,
    DETAIL_ID: (id?: string) => `/location/${id}`,
  },
  PACKAGE: {
    INDEX: "/package",
    CREATE: "/package/create",
    DETAIL: "/package/:id",
    EDIT: "/package/edit/:id",
    EDIT_ID: (id?: string) => `/package/edit/${id}`,
    DETAIL_ID: (id?: string) => `/package/${id}`,
  },

  ROLE: {
    INDEX: "/role",
    CREATE: "/role/create",
    DETAIL: "/role/:id",
    EDIT: "/role/edit/:id",
    EDIT_ID: (id?: string) => `/role/edit/${id}`,
    DETAIL_ID: (id?: string) => `/role/${id}`,
  },
  
  PRODUCT_GROUP: {
    INDEX: "/product-group",
    CREATE: "/product-group/create",
    DETAIL: "/product-group/:id",
    EDIT: "/product-group/edit/:id",
    EDIT_ID: (id?: string) => `/product-group/edit/${id}`,
    DETAIL_ID: (id?: string) => `/product-group/${id}`,
  },
};
